"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](fg:#0a84ff bg:#2c2c2e)\
[  ](bg:#0a84ff fg:#ffffff)\
[](bg:#2c2c2e fg:#0a84ff)\
$directory\
[](fg:#2c2c2e bg:#1f1f23)\
$git_branch\
$git_status\
[](fg:#1f1f23 bg:#1e1e1e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1e1e1e bg:#000000)\
$time\
[ ](fg:#000000)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#2c2c2e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1f1f23"
format = '[[ $symbol $branch ](fg:#5eb0ff bg:#1f1f23)]($style)'

[git_status]
style = "bg:#1f1f23"
format = '[[($all_status$ahead_behind )](fg:#ff6961 bg:#1f1f23)]($style)'

[time]
style = "bg:#000000"
format = '[[  $time ](fg:#a0a0a0 bg:#000000)]($style)'

[character]
success_symbol = "[➜](bold #30d158)" 
error_symbol = "[✗](bold #ff453a)"

[package]
disabled = true
